DROP DATABASE IF EXISTS taskManager;
CREATE DATABASE taskManager CHARACTER SET 'utf8';

USE taskManager;

CREATE TABLE tbl_day(
  Id TINYINT NOT NULL UNIQUE AUTO_INCREMENT,
  Name VARCHAR(10),
  PRIMARY KEY(Id)
) ENGINE=INNODB;

CREATE TABLE tbl_task(
  Id SMALLINT NOT NULL UNIQUE AUTO_INCREMENT,
  Name VARCHAR(100),
  Priority TINYINT,
  Day TINYINT,
  PRIMARY KEY(Id),
  FOREIGN KEY(Day) REFERENCES tbl_day(Id)
) ENGINE=INNODB;

GRANT ALL ON taskManager . * TO 'taskManager'@'localhost' IDENTIFIED BY 'taskManager';
FLUSH PRIVILEGES;